version: "3.8"
services:
  sqlServer:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@teste123
    ports:
      - "1433:1433"
    container_name: "Sql-Server"